    DIR_Z_MAX           =       0000_0001b 
    DIR_Z_MIN           =       0000_0010b
    DIR_Z_BTH           =       0000_0011b
    DIR_X_MAX           =       0000_0100b
    DIR_X_MIN           =       0000_1000b
    DIR_X_BTH           =       0000_1100b
    DIR_Y_MAX           =       0001_0000b
    DIR_Y_MIN           =       0010_0000b
    DIR_Y_BTH           =       0011_0000b
    DIR_XYZ_BTH         =       0011_1111b

    NO_COLLISION        =       0

    halfPlayer          =       0.5
    halfBlock           =       0.5

    X_COLLISION         =       Collision.XCollision
    Y_COLLISION         =       Collision.YCollision
    Z_COLLISION         =       Collision.ZCollision
    ALL_COLLISION       =       Collision.AllCollision