extensionAddresses:
        glGenerateMipmap        dd      ?
        glGenFramebuffers       dd      ?
        glBindFramebuffer       dd      ?
        glFramebufferTexture2D  dd      ?
        gluBuild2DMipmaps       dd      ?
        glUseProgram            dd      ?
        glDetachShader          dd      ?
        glDeleteShader          dd      ?
        glDeleteProgram         dd      ?
        glCreateShader          dd      ?
        glShaderSource          dd      ?
        glCompileShader         dd      ?
        glGetShaderiv           dd      ?
        glCreateProgram         dd      ?
        glAttachShader          dd      ?
        glLinkProgram           dd      ?
        glGetProgramiv          dd      ?
        glGetUniformLocation    dd      ?
        glUniform1f             dd      ?
        glUniform2f             dd      ?
        glUniform1i             dd      ?
        glUniformMatrix4fv      dd      ?

        glGenBuffers            dd      ?
        glBindBuffer            dd      ?  
        glBufferData            dd      ?
        glGenVertexArrays       dd      ?
        glBindVertexArray       dd      ?
        glVertexAttribPointer   dd      ?
        glEnableVertexAttribArray dd    ?
        glActiveTexture       dd      ?

extensionNames:
                        db      "glGenerateMipmap", 0
                        db      "glGenFramebuffers", 0
                        db      "glBindFramebuffer", 0
                        db      "glFramebufferTexture2D", 0
                        db      "gluBuild2DMipmaps", 0
                        db      "glUseProgram", 0
                        db      "glDetachShader", 0
                        db      "glDeleteShader", 0
                        db      "glDeleteProgram", 0
                        db      "glCreateShader", 0
                        db      "glShaderSource", 0
                        db      "glCompileShader", 0
                        db      "glGetShaderiv", 0
                        db      "glCreateProgram", 0
                        db      "glAttachShader", 0
                        db      "glLinkProgram", 0
                        db      "glGetProgramiv", 0
                        db      "glGetUniformLocation", 0
                        db      "glUniform1f", 0
                        db      "glUniform2f", 0
                        db      "glUniform1i", 0
                        db      "glUniformMatrix4fv", 0

                        db      "glGenBuffers", 0
                        db      "glBindBuffer",      0
                        db      "glBufferData",      0
                        db      "glGenVertexArrays", 0
                        db      "glBindVertexArray", 0
                        db      "glVertexAttribPointer", 0
                        db      "glEnableVertexAttribArray", 0
                        db      "glActiveTexture", 0

                        db      0 

                        GL_DEPTH_ATTACHMENT             = 0x8D00
			GL_FRAMEBUFFER                  = 0x8D40
                        GL_VERTEX_SHADER                = 0x8B31
                        GL_FRAGMENT_SHADER              = 0x8B30
                        GL_COMPILE_STATUS               = 0x8B81
                        GL_LINK_STATUS                  = 0x8B82

                        GL_ARRAY_BUFFER                 = 0x8892
                        GL_ELEMENT_ARRAY_BUFFER         = 0x8893
                        
                        
                        GL_STATIC_DRAW                  = 0x88E4
                        GL_STATIC_READ                  = 0x88E5
                        GL_STATIC_COPY                  = 0x88E6
                        GL_DYNAMIC_DRAW                 = 0x88E8
                        GL_DYNAMIC_READ                 = 0x88E9
                        GL_DYNAMIC_COPY                 = 0x88EA

                        
 GL_TEXTURE0                     =  0x84C0
 GL_TEXTURE0                     =  0x84C0
 GL_TEXTURE1                     =  0x84C1
 GL_TEXTURE2                     =  0x84C2
 GL_TEXTURE3                     =  0x84C3
 GL_TEXTURE4                     =  0x84C4
 GL_TEXTURE5                     =  0x84C5
 GL_TEXTURE6                     =  0x84C6
 GL_TEXTURE7                     =  0x84C7
 GL_TEXTURE8                     =  0x84C8
 GL_TEXTURE9                     =  0x84C9
 GL_TEXTURE10                    =  0x84CA
 GL_TEXTURE11                    =  0x84CB
 GL_TEXTURE12                    =  0x84CC
 GL_TEXTURE13                    =  0x84CD
 GL_TEXTURE14                    =  0x84CE
 GL_TEXTURE15                    =  0x84CF
 GL_TEXTURE16                    =  0x84D0
 GL_TEXTURE17                    =  0x84D1
 GL_TEXTURE18                    =  0x84D2
 GL_TEXTURE19                    =  0x84D3
 GL_TEXTURE20                    =  0x84D4
 GL_TEXTURE21                    =  0x84D5
 GL_TEXTURE22                    =  0x84D6
 GL_TEXTURE23                    =  0x84D7
 GL_TEXTURE24                    =  0x84D8
 GL_TEXTURE25                    =  0x84D9
 GL_TEXTURE26                    =  0x84DA
 GL_TEXTURE27                    =  0x84DB
 GL_TEXTURE28                    =  0x84DC
 GL_TEXTURE29                    =  0x84DD
 GL_TEXTURE30                    =  0x84DE
 GL_TEXTURE31                    =  0x84DF