
        ; Buffer for drawing objects 
        blockVAO                VAO             
        blockVBO                VBO             
        blockEBO                EBO             

        lightVAO                VAO             
        lightVBO                VBO 
        lightEBO                EBO

        ; shadowVAO               VAO             
        ; shadowVBO               VBO 
        ; shadowEBO               EBO

        interfaceVAO            VAO
        interfaceVBO            VBO
        interfaceEBO            EBO